title: Paulina Berrueto
logo: WhatsApp Image 2023-08-16 at 2.42.39 PM.jpeg
description: I am a responsible, kind person, able to work in teamS. In my previous jobs I have always stood out for my punctuality, ability to learn quickly and good productivity.
theme: jekyll-theme-minimal
background-color: #DADEDF
