title: Paulina Berrueto
logo: https://github.com/PaulinaBerrueto/Portofolio/blob/main/WhatsApp%20Image%202023-08-16%20at%202.42.39%20PM.jpeg
description: Contact
berruetopaulina@gmail.com
52 844 870 8140
theme: jekyll-theme-minimal
