title: Paulina Berrueto
logo: WhatsApp Image 2023-08-16 at 2.42.39 PM.jpeg
description: I am a responsible, kind person and able to work in a team. In my previous jobs I have always stood out for my punctuality, ability to learn quickly and good productivity.
theme: jekyll-theme-minimal
